### ISSUE TITLE
Network issue when create a Vapp

### ISSUE THREAD

**Issue by lucker6666** [vmware/pyvcloud#6]
task = vcd.create_vApp('mytestvapp', 'Windows_XP_Pro_SP3_x86_en-US', 'Windows_XP_x86_SP3' , {'--blocking': True, '--json': True, '--deploy': True, '--on': True, '--network': 'RD LAN', '--fencemode': 'bridged'})
the result,
BAD_REQUEST  The VCD entity network \"VM Network\" does not exist

seems create_vApp still using default VM Network  network? (This is for sure. https://communities.vmware.com/message/2457934)

but when i didn't configure the Network when creating Vapps and try to connect the correct network after running below codes:
myvapp.connect_vms('RD LAN', 'POOL')

It told me the network RD LAN didn't exist.

but when i run 
networks = vcd.get_networkRefs()
print networks[0].name

the result is RD LAN

**Comment by pacogomez** [comment]
should be fixed in the latest version 0.6, check documentation:

#create vApp and get the reference
vcd.create_vApp('myvapp', 'Ubuntu Server 12.04 LTS (amd64 20140927)', 'Public Catalog', {'--blocking': True, '--json': True, '--deploy': False, '--on': False, '--network': ''})
vapp = vcd.get_vApp('myvapp')

#connect vApp to org network
vcd.connect_vApp(vapp, 'AppServices-default-routed', 'bridged')

#connect the VMs
vapp.connect_vms('AppServices-default-routed', 'POOL')

#power on the vApp and VMs
vapp.poweron({'--blocking': True, '--json': True})

**Comment by lucker6666** [comment]
After running above code, the result display success, but seems still have problems,  the VM still trying to connected to previous "VM Network" network not the "RD LAN"

**Comment by pacogomez** [comment]
The vapp is connected to the VM Network, but not the VMs, to disconnect it, simply do:

vapp.disconnect_from_network('VM Network', True, True)

**Comment by pacogomez** [comment]
What version of vCD are you using?

**Comment by lucker6666** [comment]
It works after disconnect from network. thanks so much for your help.
